server:
  port: 8089
spring:
  application:
    name: ServiceB
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    leaseExpirationDurationInSeconds: 60
    leaseRenewalIntervalInSeconds: 30
  registryFetchIntervalSeconds: 10

feign:
  client:
    config:
      default:
        connectTimeout: 1000
        readTimeout: 1000
        loggerLevel: full
  hystrix:
    enabled: true

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 3000
        circuitBreaker:
          requestVolumeThreshold: 4



## feign日志打印
logging:
  level:
    com.barrywang.service.feign: debug
