server:
  port: 8089
spring:
  application:
    name: ServiceB
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    leaseExpirationDurationInSeconds: 60
    leaseRenewalIntervalInSeconds: 30

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: full
  hystrix:
    enabled: true

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 1000
        circuitBreaker:
          requestVolumeThreshold: 4



## feign日志打印
logging:
  level:
    com.barrywang.service.feign: debug
