server:
  port: 8761
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
  instance:
    leaseExpirationDurationInSeconds: 120
    leaseRenewalIntervalInSeconds: 60
  server:
      evictionIntervalTimerInMs: 5000
      enable-self-preservation: false